#!/usr/bin/env zsh

# WHAT I WANT
# ailiases
# prompt l1: --- user@machine --- branch@env  l2: pwd $
# search history (?oh-my-zsh?)

if [[ "$ZPROF" = true ]]; then
        zmodload zsh/zprof
fi

source $HOME/.zsh/exports.zsh

if [ -f "$HOME/.zsh_plugins.sh" ]; then
        source $HOME/.zsh_plugins.sh
else
        echo "Bundling zsh plugins..."
        # antibody bundle <$HOME/.zsh/plugins.txt >$HOME/.zsh_plugins.sh
        brew bundle <$HOME/.zsh/plugins.txt >$HOME/.zsh_plugins.sh
        source $HOME/.zsh_plugins.sh
fi

source $HOME/.zsh/init.zsh
# source $HOME/.zsh/evals.zsh
source $HOME/.zsh/history.zsh
# source $HOME/.zsh/stack.zsh
source $HOME/.zsh/keys.zsh
source $HOME/.zsh/aliases.zsh
# source $HOME/.zsh/gpg-agent.zsh

# if [ -f "$HOME/.cargo/env" ]; then
#         source $HOME/.cargo/env
# fi

# base16 theme
# base16_gruvbox-dark-hard

if (($+commands[fortune])); then
        fortune
fi

if [[ "$ZPROF" = true ]]; then
        zprof
fi

# export PS1="[@\[$(tput sgr0)\]\[\033[38;5;45m\]\W\[$(tput sgr0)\]] \\$ \[$(tput sgr0)\]"
PROMPT="--- %n@%m ---\n [%1~] $# "
